# Generated by Django 3.2.16 on 2023-02-08 16:36

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='favouriteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('favourite', models.IntegerField(choices=[(0, 'Not Added'), (1, 'Added')], default=0)),
            ],
        ),
    ]
