# Generated by Django 3.2.16 on 2023-02-09 15:28

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrintStore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('featured_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('favourite', models.IntegerField(choices=[(0, 'Not Added'), (1, 'Added')], default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='favouriteImage',
        ),
    ]
