# Generated by Django 3.2.18 on 2023-03-22 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PrintStore', '0003_artsyphotos_productionphotots'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductionPhotots',
            new_name='ProductionPhotos',
        ),
    ]
