# Generated by Django 3.2.18 on 2023-04-03 14:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PrintStore', '0004_rename_productionphotots_productionphotos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artsyphotos',
            name='favourite',
        ),
        migrations.AddField(
            model_name='artsyphotos',
            name='favourite',
            field=models.ManyToManyField(blank=True, choices=[(False, 'Not Added'), (True, 'Added')], related_name='artsy_favourite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='photos',
            name='favourite',
        ),
        migrations.AddField(
            model_name='photos',
            name='favourite',
            field=models.ManyToManyField(blank=True, choices=[(False, 'Not Added'), (True, 'Added')], related_name='favourites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='productionphotos',
            name='favourite',
        ),
        migrations.AddField(
            model_name='productionphotos',
            name='favourite',
            field=models.ManyToManyField(blank=True, choices=[(False, 'Not Added'), (True, 'Added')], related_name='production_favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
