# Generated by Django 3.2.18 on 2023-04-03 16:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PrintStore', '0006_auto_20230403_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artsyphotos',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='artsy_photos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='photos',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='favourited_photos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productionphotos',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='production_photos', to=settings.AUTH_USER_MODEL),
        ),
    ]
